apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-gui-tester
spec:
  # storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data" # The path inside the Minikube VM
    type: DirectoryOrCreate
