name: Apply Infrastructure
on:
  push:
    branches: [main]
    paths: ['k8s/**']
  workflow_dispatch:

jobs:
  apply:
    runs-on: [self-hosted, k8s-lab]
    steps:
      - uses: actions/checkout@v4

      - name: Get Kubectl Reference
        run: export KUBECONFIG=/vagrant/kubeconfig

      - name: Apply manifests
        run: |
          kubectl apply -R -f k8s/namespaces
          kubectl apply -R -f k8s/apps -n k8s-lab
