name: Apply Infrastructure
on:
  push:
    branches: [main]
    paths: ['cluster-infra/k8s/**']
  workflow_dispatch:

jobs:
  apply:
    runs-on: [self-hosted, k8s-lab]
    steps:
      - uses: actions/checkout@v4

      - name: Apply manifests
        run: |
          export KUBECONFIG=/vagrant/kubeconfig
          kubectl apply -R -f cluster-infra/k8s/ -n k8s-lab
